/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProgramRouteImport } from './routes/_authenticated/program'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletActivityRouteImport } from './routes/wallet.activity'
import { Route as WalletProfileRouteImport } from './routes/wallet.profile'
import { Route as WalletQrRouteImport } from './routes/wallet.qr'
import { Route as WalletRewardsRouteImport } from './routes/wallet.rewards'
import { Route as WalletJoinTokenRouteImport } from './routes/wallet.join.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramRoute = AuthenticatedProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRoute,
} as any)
const WalletActivityRoute = WalletActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => WalletRoute,
} as any)
const WalletProfileRoute = WalletProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WalletRoute,
} as any)
const WalletQrRoute = WalletQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => WalletRoute,
} as any)
const WalletRewardsRoute = WalletRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => WalletRoute,
} as any)
const WalletJoinTokenRoute = WalletJoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => WalletRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/wallet': typeof WalletRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/program': typeof AuthenticatedProgramRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallet/activity': typeof WalletActivityRoute
  '/wallet/profile': typeof WalletProfileRoute
  '/wallet/qr': typeof WalletQrRoute
  '/wallet/rewards': typeof WalletRewardsRoute
  '/wallet/': typeof WalletIndexRoute
  '/wallet/join/$token': typeof WalletJoinTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/program': typeof AuthenticatedProgramRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallet/activity': typeof WalletActivityRoute
  '/wallet/profile': typeof WalletProfileRoute
  '/wallet/qr': typeof WalletQrRoute
  '/wallet/rewards': typeof WalletRewardsRoute
  '/wallet': typeof WalletIndexRoute
  '/wallet/join/$token': typeof WalletJoinTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/wallet': typeof WalletRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/program': typeof AuthenticatedProgramRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/wallet/activity': typeof WalletActivityRoute
  '/wallet/profile': typeof WalletProfileRoute
  '/wallet/qr': typeof WalletQrRoute
  '/wallet/rewards': typeof WalletRewardsRoute
  '/wallet/': typeof WalletIndexRoute
  '/wallet/join/$token': typeof WalletJoinTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/wallet'
    | '/customers'
    | '/dashboard'
    | '/onboarding'
    | '/program'
    | '/rewards'
    | '/scan'
    | '/settings'
    | '/transactions'
    | '/wallet/activity'
    | '/wallet/profile'
    | '/wallet/qr'
    | '/wallet/rewards'
    | '/wallet/'
    | '/wallet/join/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/customers'
    | '/dashboard'
    | '/onboarding'
    | '/program'
    | '/rewards'
    | '/scan'
    | '/settings'
    | '/transactions'
    | '/wallet/activity'
    | '/wallet/profile'
    | '/wallet/qr'
    | '/wallet/rewards'
    | '/wallet'
    | '/wallet/join/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/wallet'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/program'
    | '/_authenticated/rewards'
    | '/_authenticated/scan'
    | '/_authenticated/settings'
    | '/_authenticated/transactions'
    | '/wallet/activity'
    | '/wallet/profile'
    | '/wallet/qr'
    | '/wallet/rewards'
    | '/wallet/'
    | '/wallet/join/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  WalletRoute: typeof WalletRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/program': {
      id: '/_authenticated/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof AuthenticatedProgramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/activity': {
      id: '/wallet/activity'
      path: '/activity'
      fullPath: '/wallet/activity'
      preLoaderRoute: typeof WalletActivityRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/profile': {
      id: '/wallet/profile'
      path: '/profile'
      fullPath: '/wallet/profile'
      preLoaderRoute: typeof WalletProfileRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/qr': {
      id: '/wallet/qr'
      path: '/qr'
      fullPath: '/wallet/qr'
      preLoaderRoute: typeof WalletQrRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/rewards': {
      id: '/wallet/rewards'
      path: '/rewards'
      fullPath: '/wallet/rewards'
      preLoaderRoute: typeof WalletRewardsRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/join/$token': {
      id: '/wallet/join/$token'
      path: '/join/$token'
      fullPath: '/wallet/join/$token'
      preLoaderRoute: typeof WalletJoinTokenRouteImport
      parentRoute: typeof WalletRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProgramRoute: typeof AuthenticatedProgramRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProgramRoute: AuthenticatedProgramRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface WalletRouteChildren {
  WalletActivityRoute: typeof WalletActivityRoute
  WalletProfileRoute: typeof WalletProfileRoute
  WalletQrRoute: typeof WalletQrRoute
  WalletRewardsRoute: typeof WalletRewardsRoute
  WalletIndexRoute: typeof WalletIndexRoute
  WalletJoinTokenRoute: typeof WalletJoinTokenRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletActivityRoute: WalletActivityRoute,
  WalletProfileRoute: WalletProfileRoute,
  WalletQrRoute: WalletQrRoute,
  WalletRewardsRoute: WalletRewardsRoute,
  WalletIndexRoute: WalletIndexRoute,
  WalletJoinTokenRoute: WalletJoinTokenRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  WalletRoute: WalletRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
